### ISSUE TITLE
Unable to get_temperature() while start_reading()

### ISSUE THREAD

**Issue by HanYangZhao** [gotthardp/python-mercuryapi#92] opened 2019-11-05 15:50 UTC
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./thingMagicRead2.py", line 48, in heartbeat
    temp = reader.get_temperature()
RuntimeError: Unimplemented feature
`

I'm assuming this is an error returned from the MercuryAPI?

**Comment by gotthardp** [comment] 2019-11-05 17:00
Yes. It is likely not supported by your reader, or the reader is in some state in which it is not allowed to call that function. I cannot do much about that.

**Comment by natcl** [comment] 2019-11-05 17:05
Seems to be a duplicate of #71

**Comment by HanYangZhao** [comment] 2019-11-05 18:22
I dug a bit further with the URA assistant by printing the serial log and was able to see the temperature being sent by the reader. So I went to check the doc and found the following 
![temprature_status](https://user-images.githubusercontent.com/4143538/68234445-3ab89800-ffcf-11e9-83d8-634e1482c64d.png)

**Comment by gotthardp** [comment] 2019-11-05 19:28
Does this suggest something?

**Comment by HanYangZhao** [comment] 2019-11-05 19:53
![statusListener](https://user-images.githubusercontent.com/4143538/68240680-575acd00-ffdb-11e9-990f-fdf06a3d0196.png)

From what I understand, the temperature is collected by the statusListener, It seems to be similar to the ReadListener used for tag reading. I was however unable to find the format of the data that's being passed(something similar to TMR_TagReadData).

**Comment by gotthardp** [comment] 2019-11-06 12:01
Yeah, it seems that TMR_addStatsListener could be used, but it is not implemented right now. Contributions are welcome :)

**Comment by HanYangZhao** [comment] 2019-11-07 22:53
I have attempted to add the TMR_addStatsListener on my [fork](https://github.com/HanYangZhao/python-mercuryapi). So far it doesn't return any error, but the callback doesn't seem to get called. Maybe you have some insights?

**Comment by gotthardp** [comment] 2019-11-08 09:04
Unfortunatelly not.

**Comment by gotthardp** [comment] 2019-11-11 09:51
This was fixed by @HanYangZhao in https://github.com/gotthardp/python-mercuryapi/commit/7f493198056824cba9f8b11e89eadf46c4720de2. Function `enable_stats` may now e used to retrieve temp (and other stats) during reading. Thanks a lot again!

**Closed by gotthardp** 2019-11-11 09:51 UTC
Labels: duplicate, question
