### ISSUE TITLE
Getting user memory data

### ISSUE THREAD

**Issue by nitayhas** [gotthardp/python-mercuryapi#19] opened 2018-02-18 14:56 UTC
Hey,
Is it possible to get the user memory data?
I tried to play with the code(of mercury.c) a little bit but with no luck.

Thank you.

**Comment by gotthardp** [comment] 2018-02-19 15:47
Hey. This feature is not yet implemented, I am afraid.

**Comment by gotthardp** [comment] 2018-02-19 15:48
Duplicate of #8

**Comment by gotthardp** [comment] 2018-09-11 16:49
Hello. Sorry for the delay. I just implemented the read access to memory banks. See the `bank` argument of the set_read_plan.

**Closed by gotthardp** 2018-09-11 16:49 UTC
Labels: duplicate, enhancement
